version: '3'

services:
  app:
    container_name: pvzService
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db_container
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:  
  pgdata: {}
